[package]
name = "toktokenizer"
version = "0.1.1"
edition = "2021"

[lib]
name = "toktokenizer"

[dependencies]
tqdm = "0.7.0"
serde_json = "1.0.117"
serde = { version = "1.0", features = ["derive"] }
rustc-hash = "2.1.1"

[dev-dependencies]
fake = "3.1.0"
